declare type ColorCode = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z";
export declare const trustScriptRegex: RegExp;
export declare const scriptRegex: RegExp;
export declare const keyValueRegex: RegExp;
export declare function rgb(r: number, g: number, b: number, text: string): string;
export declare function rgbNoEnd(r: number, g: number, b: number, text: string): string;
export declare function backRgb(r: number, g: number, b: number, text: string): string;
export declare function underline(text: string): string;
export declare function bold(text: string): string;
export declare function italic(text: string): string;
export declare function strikethrough(text: string): string;
export declare function logNoNL(args?: string): void;
export declare function log(args?: string): void;
export declare function logInput(args?: string): void;
export declare function hackmudColor(colorCode: ColorCode, text: string, input: boolean): string;
export declare function scriptColor(scriptor: string, user: string, script: string, text: string): string;
export declare function getUserColor(user: string): string;
export declare function parse(str: string, input: boolean): string;
export {};
